### ISSUE TITLE
timeline plugin for archive search 

### ISSUE THREAD

**Issue by ElizabethLui** [DocNow/twarc-timelines#1]
just wondering if the timeline plugin could be used for full-archive search (i.e. through search end-point instead of timeline end-point)? If so, I'd imagine the plugin would enable us to fetch the timelines from a specific period of time for a list of users stored in txt file (similar to how the timeline plugin works for now). Thanks a lot!!!

**Comment by edsu** [comment]
I've just uploaded twarc-timelines v0.0.4 which adds a `--use-search` option. It will use the search api to fetch as many of the users's tweets as possible from the search/all API endpoint, and so isn't restricted to the last 3,200 from the timeline API. I didn't add options for specifying the time range, but please reopen or add a new issue if that's a problem.

    twarc2 timelines users.txt --output-dir timelines --use-search
