### ISSUE TITLE
User Does Not Exist

### ISSUE THREAD

**Issue by willturn001** [DocNow/twarc-timelines#6]
When the module encounters a user which no longer exists, it terminates. I suggest either skipping the non-existent user or have it return to the output file "this user does not exist"

**Comment by igorbrigadir** [comment]
What exact command did you run? Just so we keep track and make sure we cover all cases.

I think for this plugin in makes sense to show a warning, log it, and continue on with collection.

**Comment by igorbrigadir** [comment]
It's fixed in that PR but i'll need @edsu to make the new release on pypi i think! If you want to get it working immediately, you can:

```
git clone https://github.com/DocNow/twarc-timeline-archive.git
git checkout resume-failures
pip install -e .
```

**Comment by igorbrigadir** [comment]
Up on pypi now @willturn001! `pip3 install --upgrade twarc-timeline-archive` should work!

**Comment by willturn001** [comment]
> Up on pypi now @willturn001! `pip3 install --upgrade twarc-timeline-archive` should work!

Thanks so much!
